excluded:
  # Exclude this package specifically
  - cn.amazon.mShop.android
  # Exclude all packages starting with com.microsoft
  - regex: ^com\.microsoft\..*

included:
  # Include this package specifically
  - com.alicom.smartdial
  # Include all packages starting with com.heytap by PROCESS-NAME-REGEX
  - regex: ^com\.heytap\..*
